### ISSUE TITLE
Feature Request: Inverse status

### ISSUE THREAD

**Issue by durosity** [Ghawken/HomeKitLink-Siri#7] opened 2022-05-06 20:25 UTC
**Describe the bug**
Option per published device to inverse its status, eg off would display as on in HomeKit and vice versa

**To Reproduce**
Some devices I have, eg a virtual device for a Garage Door result in HomeKit showing the door as being open when it's actually closed, and vice versa.

**Expected behavior**
N/A

**Screenshots**
N/A

**Device Information**
N/A

**If Camera Stream Related**
N/A

**Additional context**
N/A

**Comment by Ghawken** [comment] 2022-05-06 21:59
Hi Would prefer not to make this change for every device, as it is pretty major - most should be fine eg on = on.

There is a lot of potential impact of checking every device for a inverse check before turning on or turning off.  It doesn’t take much time but it all add’s up to layers and more layers.  Particularly when talking about communication backwards and forwards from HomeKit to Indigo.   My thoughts here have been to keep as simple and quick as possible, rather than adding multiple checks before commands are executed.

You could create masquerade device, or a new reversed virtual device or other to cover these occasional fringe cases.

What device in particular?
If it is just Garage Door - would consider adding for it, and probably blinds when get to it, as probably need same.

**Comment by durosity** [comment] 2022-05-06 23:17
So far I've only had it with the garage door.  Now here's the interesting thing, it's a virtual device but its status is off which I would have thought would have automatically translated to closed.  Perhaps it's a bug?

Here's the device details in case it helps:

batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : pseudoRelay
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 171631128
globalProps : MetaProps : (dict)
     com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
          HomeKit_audioSelector : false (bool)
          HomeKit_bridgeUniqueID : 549226 (integer)
          HomeKit_deviceSensor : onOffState (string)
          HomeKit_deviceSubtype : GarageDoor (string)
          HomeKit_publishDevice : true (bool)
          HomeKit_tempSelector : false (bool)
          homekit-name : Door (string)
     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
          doToggle : true (bool)
          executionType : actionGroup (string)
          offActionGroup : 1536789117 (string)
          onActionGroup : 1536789117 (string)
          statusRequestActionGroup :  (string)
          statusVariable : 203820908 (string)
          supportsStatusRequest : true (bool)
          toggleActionGroup : 1536789117 (string)
id : 1396191405
lastChanged : 2022-05-06 23:12:53
lastSuccessfulComm : 2022-05-06 23:12:53
ledStates : []
model : Virtual On/Off Device
name : Garage - Door
onState : False
ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
     doToggle : true (bool)
     executionType : actionGroup (string)
     offActionGroup : 1536789117 (string)
     onActionGroup : 1536789117 (string)
     statusRequestActionGroup :  (string)
     statusVariable : 203820908 (string)
     supportsStatusRequest : true (bool)
     toggleActionGroup : 1536789117 (string)
pluginId : com.perceptiveautomation.indigoplugin.devicecollection
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None

**Comment by durosity** [comment] 2022-05-06 23:19
On a side note I do have 1 window motor which shows as On for closed and Off for Open because that one window opens the opposite way to the others.  I guess when it gets implemented I'll need to set up a masquerade.

**Comment by Ghawken** [comment] 2022-05-06 23:22
If its a virtual device - these don’t update their onOffStates unless you manually update them. (Discovered this recently when testing)
Eg. Turn on/turn off - doesn’t actually change the state of the virtual device - still shows off/on -  it still show what it was
There is a separate command to change VD, statethat needs to be incorporated in the action group that you are running.

I would guess that that is the issue - even though you are running the command - the state of the VD doesn’t change in which case no way for HKLS to know about.

But coming back to off and on
Off - Open in HomeKit
On - closed in HomeKit

Probably makes sense for HomeKit contact sensors - door/window etc — when closed - link closed/on, open - off.
Seems same applies to doors..

**Comment by durosity** [comment] 2022-05-07 09:38
Ah well that'll explain it.  I've updated my triggers to include an action to update the on/off state!

However I'm a bit confused, to me Off = Open and On = Closed seems the opposite of what makes logical sense in my head.  For example all my blinds have off as closed and on as open, and same for the window motors where on means open and closed is off.  That will be a bit of a nightmare when that gets implemented in the plugin.. :/

**Comment by Ghawken** [comment] 2022-05-07 09:49
I think reverse does make sense when thinking about contact sensors - the little magnetic ones - magnet closes == On, and magnet leaves open contact == Off.

Blinds - I got confused with as well with I updating RFXCOM to support my blinds a while back.  Did add a reverse logic to that RFXCOM blind device to deal with the logic that didn’t seem to make sense.

I presume Homekit uses the same logic with blinds — however in my case within the RFXCOM blind device I can reverse.   The problem with blinds is if set to 80% and logic reversed - is that 80% open, now 20% open etc.   So the reversing affects more than just on/off.

**Comment by durosity** [comment] 2022-05-07 10:42
I'm sure I read someone having this exact debate on a forum 10 years ago.. there's no right or wrong way.. both sets of logic work.. if the blind is 80% is that open, or 80% closed?  Alas this is why I think we need to have a way to inverse the status in the plugin (which to be fair is how it was set up on C4Ws HKB plugin, although I appreciate that's a right ballache for you).

**Comment by durosity** [comment] 2022-05-07 21:34
So I've done a bit of rewiring of the 2 devices that I found work the opposite to the way the others work, so now at least it's consistent.  If you can add an invert status per type of device then that should work now 😊

**Comment by Ghawken** [comment] 2022-05-08 06:37
Ok.
I should be able to do a Inverse Relationship for each HomeKit individual device - so they can be different.

**Can you post the log of the blind devices you are using?  ** 
More the better.

I presume they are Dimmers?  Mine are - but don't necessarily want to guess...

Also the reverse logic ones - does that mean setting to 80% -- ends up being 20% in Indigo?

**Comment by Ghawken** [comment] 2022-05-08 10:26
Have a try of 0.2.28
Supporting blinds and reverse option for
Blinds - enabled per device.  Supporting indigo dimmer devices and relays/On-off devices 
This version also automatically adds battery support for all sensor devices -
Which I got sidetracked on as was more interesting … but managed to get back to the blinds 

Will likely need to use showalloptions and select blind as HomeKit device

If can still give me device logging for your blind devices as above - should be able to add them to automatically selected as blind.  But once entered doesn’t matter:  Can go from inverse to not and shouldn’t matter to HomeKit if need to change settings around  once published.

**Comment by durosity** [comment] 2022-05-08 20:15
Sorry was out all day so only just saw these replies

Here's the device log:

batteryLevel : None
blueLevel : None
brightness : 0
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
defaultBrightness : 100
description : 
deviceTypeId : zwDimmerType
displayStateId : brightnessLevel
displayStateImageSel : DimmerOff
displayStateValRaw : 0
displayStateValUi : 0
enabled : True
energyAccumBaseTime : 2021-04-24 15:46:18
energyAccumTimeDelta : 30870970
energyAccumTotal : 0.0
energyCurLevel : 0.0
errorState : 
folderId : 1108825678
globalProps : MetaProps : (dict)
     com.perceptiveautomation.indigoplugin.zwave : (dict)
          SupportsEnergyMeter : true (bool)
          SupportsEnergyMeterCurPower : true (bool)
          SupportsEnergyMeterReset : true (bool)
          SupportsGasMeterReset : true (bool)
          SupportsWaterMeterReset : true (bool)
          address : 68 (integer)
          indigoObjVersion : 10 (integer)
          modelNameAndFirmware : Flush Shutter DC (ZMNHOD), firmware 1.01 (string)
          propsPushTickler : 1 (string)
          tempAlwaysFalse : false (bool)
          userConfigVal071 : 0 (integer)
          userConfigVal072 : 150 (integer)
          userConfigVal074 : 10 (integer)
          userConfigVal076 : 6 (integer)
          userConfigVal078 : false (bool)
          userConfigVal110 : 0 (integer)
          userConfigVal120 : 0 (integer)
          userEnergyPollingEnabled : false (bool)
          userPollAfterActivity : true (bool)
          userPollInterval : 0 (integer)
          userPollingEnabled : true (bool)
          userWakeInterval : 60 (integer)
          version : 1.01 (string)
          zwAppVersMajor : 1 (integer)
          zwAppVersMinor : 1 (integer)
          zwAssociationsMap : (dict)
               g1 : (list)
                    Item : 1 (integer)
               g2 : (list)
               g3 : (list)
               g4 : (list)
               g5 : (list)
               g6 : (list)
               g7 : (list)
               g8 : (list)
               g9 : (list)
                    Item : 1 (integer)
          zwAssociationsMapStr : 1:[1] 2:[] 3:[] 4:[] 5:[] 6:[] 7:[] 8:[] 9:[1] (string)
          zwClassCmdBase : 38 (integer)
          zwClassCmdMap : (dict)
               c112 : 1 (integer)
               c114 : 1 (integer)
               c115 : 1 (integer)
               c133 : 1 (integer)
               c134 : 1 (integer)
               c142 : 1 (integer)
               c32 : 1 (integer)
               c37 : 1 (integer)
               c38 : 3 (integer)
               c39 : 1 (integer)
               c50 : 4 (integer)
               c89 : 1 (integer)
               c90 : 1 (integer)
               c94 : 1 (integer)
          zwClassCmdMapStr : 20v1 25v1 26v3 27v1 32v4 8Ev1 70v1 72v1 73v1 5Ev1 59v1 5Av1 86v1 85v1 (string)
          zwClassIds : (list)
               Item : 4 (integer)
               Item : 17 (integer)
               Item : 7 (integer)
          zwClassInstanceCountMap : (dict)
          zwClassInstanceCountMapStr : - none - (string)
          zwClassName : Motor Control Class C (string)
          zwConfigVals : (dict)
               p110 : 0 (integer)
               p120 : 0 (integer)
               p71 : 0 (integer)
               p72 : 150 (integer)
               p74 : 10 (integer)
               p76 : 6 (integer)
          zwConfigValsStr : 120:0 71:0 72:150 74:10 76:6 110:0 (string)
          zwDevSubIndex : 0 (integer)
          zwEncryptClassCmdMap : (dict)
          zwEncryptClassCmdMapStr : - none - (string)
          zwEncryptionStatusStr : Not Supported (string)
          zwEndpointClassMap : (dict)
          zwEndpointClassMapStr : - none - (string)
          zwEndpointDevTypeMap : (dict)
          zwEndpointDevTypeMapStr : - none - (string)
          zwFeatureListStr : routing, beaming, energyMeter (string)
          zwLibType : 3 (integer)
          zwManufactureId : 345 (integer)
          zwManufactureName : Qubino (string)
          zwMeterSubTypeFlags : 5 (integer)
          zwMeterSupportsReset : true (bool)
          zwMeterType : 1 (integer)
          zwModelDefnVers : 3 (integer)
          zwModelId : 196691 (integer)
          zwModelName : Flush Shutter DC (ZMNHOD) (string)
          zwNodeNeighbors : (list)
               Item : 10 (integer)
               Item : 12 (integer)
               Item : 17 (integer)
               Item : 18 (integer)
               Item : 29 (integer)
               Item : 33 (integer)
               Item : 51 (integer)
               Item : 54 (integer)
               Item : 84 (integer)
               Item : 86 (integer)
               Item : 103 (integer)
          zwNodeNeighborsStr : 10, 12, 17, 18, 29, 33, 51, 54, 84, 86, 103 (string)
          zwProtoVersMajor : 4 (integer)
          zwProtoVersMinor : 5 (integer)
          zwShowDumpDevToLog : true (bool)
          zwShowEnergyPollingUI : true (bool)
          zwShowMainUI : true (bool)
          zwShowManualModifyConfigParmUI : false (bool)
          zwShowPollingUI : true (bool)
          zwShowSubmitModelInfoUI : false (bool)
          zwShowWakeIntervalUI : false (bool)
          zwWakeInterval : 0 (integer)
greenLevel : None
id : 1498113616
lastChanged : 2022-05-01 11:47:26
lastSuccessfulComm : 2022-05-01 11:47:26
ledStates : []
model : Flush Shutter DC (ZMNHOD)
name : Guest Bedroom - Venetian Blinds
onBrightensToDefaultToggle : False
onBrightensToLast : True
onState : False
ownerProps : com.perceptiveautomation.indigoplugin.zwave : (dict)
     SupportsEnergyMeter : true (bool)
     SupportsEnergyMeterCurPower : true (bool)
     SupportsEnergyMeterReset : true (bool)
     SupportsGasMeterReset : true (bool)
     SupportsWaterMeterReset : true (bool)
     address : 68 (integer)
     indigoObjVersion : 10 (integer)
     modelNameAndFirmware : Flush Shutter DC (ZMNHOD), firmware 1.01 (string)
     propsPushTickler : 1 (string)
     tempAlwaysFalse : false (bool)
     userConfigVal071 : 0 (integer)
     userConfigVal072 : 150 (integer)
     userConfigVal074 : 10 (integer)
     userConfigVal076 : 6 (integer)
     userConfigVal078 : false (bool)
     userConfigVal110 : 0 (integer)
     userConfigVal120 : 0 (integer)
     userEnergyPollingEnabled : false (bool)
     userPollAfterActivity : true (bool)
     userPollInterval : 0 (integer)
     userPollingEnabled : true (bool)
     userWakeInterval : 60 (integer)
     version : 1.01 (string)
     zwAppVersMajor : 1 (integer)
     zwAppVersMinor : 1 (integer)
     zwAssociationsMap : (dict)
          g1 : (list)
               Item : 1 (integer)
          g2 : (list)
          g3 : (list)
          g4 : (list)
          g5 : (list)
          g6 : (list)
          g7 : (list)
          g8 : (list)
          g9 : (list)
               Item : 1 (integer)
     zwAssociationsMapStr : 1:[1] 2:[] 3:[] 4:[] 5:[] 6:[] 7:[] 8:[] 9:[1] (string)
     zwClassCmdBase : 38 (integer)
     zwClassCmdMap : (dict)
          c112 : 1 (integer)
          c114 : 1 (integer)
          c115 : 1 (integer)
          c133 : 1 (integer)
          c134 : 1 (integer)
          c142 : 1 (integer)
          c32 : 1 (integer)
          c37 : 1 (integer)
          c38 : 3 (integer)
          c39 : 1 (integer)
          c50 : 4 (integer)
          c89 : 1 (integer)
          c90 : 1 (integer)
          c94 : 1 (integer)
     zwClassCmdMapStr : 20v1 25v1 26v3 27v1 32v4 8Ev1 70v1 72v1 73v1 5Ev1 59v1 5Av1 86v1 85v1 (string)
     zwClassIds : (list)
          Item : 4 (integer)
          Item : 17 (integer)
          Item : 7 (integer)
     zwClassInstanceCountMap : (dict)
     zwClassInstanceCountMapStr : - none - (string)
     zwClassName : Motor Control Class C (string)
     zwConfigVals : (dict)
          p110 : 0 (integer)
          p120 : 0 (integer)
          p71 : 0 (integer)
          p72 : 150 (integer)
          p74 : 10 (integer)
          p76 : 6 (integer)
     zwConfigValsStr : 120:0 71:0 72:150 74:10 76:6 110:0 (string)
     zwDevSubIndex : 0 (integer)
     zwEncryptClassCmdMap : (dict)
     zwEncryptClassCmdMapStr : - none - (string)
     zwEncryptionStatusStr : Not Supported (string)
     zwEndpointClassMap : (dict)
     zwEndpointClassMapStr : - none - (string)
     zwEndpointDevTypeMap : (dict)
     zwEndpointDevTypeMapStr : - none - (string)
     zwFeatureListStr : routing, beaming, energyMeter (string)
     zwLibType : 3 (integer)
     zwManufactureId : 345 (integer)
     zwManufactureName : Qubino (string)
     zwMeterSubTypeFlags : 5 (integer)
     zwMeterSupportsReset : true (bool)
     zwMeterType : 1 (integer)
     zwModelDefnVers : 3 (integer)
     zwModelId : 196691 (integer)
     zwModelName : Flush Shutter DC (ZMNHOD) (string)
     zwNodeNeighbors : (list)
          Item : 10 (integer)
          Item : 12 (integer)
          Item : 17 (integer)
          Item : 18 (integer)
          Item : 29 (integer)
          Item : 33 (integer)
          Item : 51 (integer)
          Item : 54 (integer)
          Item : 84 (integer)
          Item : 86 (integer)
          Item : 103 (integer)
     zwNodeNeighborsStr : 10, 12, 17, 18, 29, 33, 51, 54, 84, 86, 103 (string)
     zwProtoVersMajor : 4 (integer)
     zwProtoVersMinor : 5 (integer)
     zwShowDumpDevToLog : true (bool)
     zwShowEnergyPollingUI : true (bool)
     zwShowMainUI : true (bool)
     zwShowManualModifyConfigParmUI : false (bool)
     zwShowPollingUI : true (bool)
     zwShowSubmitModelInfoUI : false (bool)
     zwShowWakeIntervalUI : false (bool)
     zwWakeInterval : 0 (integer)
pluginId : com.perceptiveautomation.indigoplugin.zwave
pluginProps : emptyDict : (dict)
protocol : ZWave
redLevel : None
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     accumEnergyTimeDelta : 30870970 (integer)
     accumEnergyTimeDelta.ui : 30870970 seconds (string)
     accumEnergyTotal : 0 (real)
     accumEnergyTotal.ui : 0.0 kWh (string)
     brightnessLevel : 0 (integer)
     curEnergyLevel : 0 (real)
     curEnergyLevel.ui : 0.0 W (string)
     onOffState : off (on/off bool)
subModel : ui=Shutter Position
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsColor : False
supportsRGB : False
supportsRGBandWhiteSimultaneously : False
supportsStatusRequest : True
supportsTwoWhiteLevels : False
supportsTwoWhiteLevelsSimultaneously : False
supportsWhite : False
supportsWhiteTemperature : False
version : 1.01
whiteLevel : None
whiteLevel2 : None
whiteTemperature : None

**Comment by durosity** [comment] 2022-05-08 20:21
I've also just tested out the new version with blinds support and the reverse status works, including the %.  I am however having a bit of a lag with it where the spinning wheel is appearing when opening/closing and setting different % levels.  Now the blind responds immediately, so I presume it's HomeKit awaiting an update from the hub.  I can't replicate this behaviour with a dimmer bulb which updates immediately.  I get no noticeable delays when controlling the blinds directly in Indigo.

**Comment by Ghawken** [comment] 2022-05-08 21:07
Thats probably because it is waiting for the blinds state to be completed, before its updated.

Basically - its homekit says close to 50% — 50% wanted” updates it own UI to show wheel - send to indigo - indigo actions — 50% reached - back to homekit that target reached.
Lights are quite a lot quicker I would guess, because they are a lot quicker.
The HomeKit UI doesn’t have to stay open - as as long are responding quickly - and everything has been geared towards that speed.

Unless blinds are lightning fast they will take a bit to close.  Alternative is to always register that it closed without problem, even it didn’t - not as good…

I think what I have just said above is - its expected!

I’ll have a look at device types - more the merrier.  Not quite sure what else blinds could be expect Dimmer type…. New version should also support VD and relays as blinds

**Comment by durosity** [comment] 2022-05-08 22:01
Cool, well I'll be switching my blinds and most other devices over from HKB tomorrow so will be able to give them a proper run over the next few days and I'll see if any problems arise from the delay or not.  I had one instance where it didn't stop spinning at all, had to force restart the plugin.  Not been able to replicate yet though.

Would it be possible to add the inverse state for garage doors too?  

Also are you planning to implement window motors (works basically same way as blinds)

**Comment by Ghawken** [comment] 2022-05-09 00:42
Garagedoors - they are just on/off devices - so VD etc. or masquerade would really cover that.  I'd prefer not to add to many levels of complexity.  But will have a look - the config stuff is there - so may be straightforward.

Spinning wheel - the risk with the approach of waiting for device to be confirmed as set - is if the device is Off, and HomeKit thinks is on.   (maybe not updated as yet, just started App)  When you go to turn off in Homekit, the spinning wheel will last forever - as no device change occurs/update.  Can then turn on/off in HomeKit app to sync/fix - but this really shouldn't happen unless in fringe cases.
Haven't seen any need to restart the plugin for some time.  Would be interested in that was the case.


Window Motors:
As you say - are very similar to blinds - are they Zwave dimmers as well?

**Comment by Ghawken** [comment] 2022-05-09 11:27
Window device support - I have added in latest - essentially a copy of Blinds ..

**Closed as completed** 2022-05-13 22:40 UTC

**Comment by durosity** [comment] 2022-05-13 23:38
Sorry for late reply, not had a great week.

All seems to be working well!  Would it be possible to add inverse state for garage doors anyway?  I just hate having duplicate devices in my system for that kinda reason.. it's probably just a bit OCD but it always feels wrong to me 😅
